name: Test & Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with coverage
        run: mvn clean verify

      - name: Show coverage percentage
        run: |
          if [ -f target/site/jacoco/jacoco.xml ]; then
            COVERED=$(grep '<counter type="LINE"' target/site/jacoco/jacoco.xml | sed -n 's/.*covered="\([0-9]*\)".*/\1/p')
            MISSED=$(grep '<counter type="LINE"' target/site/jacoco/jacoco.xml | sed -n 's/.*missed="\([0-9]*\)".*/\1/p')

            if [ -n "$COVERED" ] && [ -n "$MISSED" ] && [ "$((COVERED + MISSED))" -ne 0 ]; then
              TOTAL=$((COVERED + MISSED))
              PERCENT=$(awk "BEGIN { printf \"%.2f\", ($COVERED / $TOTAL) * 100 }")
              echo "Cobertura de líneas: $PERCENT%"
            else
              echo "No se pudo calcular la cobertura de líneas (valores no encontrados)."
            fi
          else
            echo "Archivo jacoco.xml no encontrado. Asegúrate de que 'mvn verify' lo genera correctamente."
          fi
      
