name: Test & Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with coverage
        run: mvn clean verify

      - name: Show coverage percentage
        run: |
          LINE_COVERAGE=$(grep -A 1 '<counter type="LINE"' target/site/jacoco/jacoco.xml | grep -oP 'covered="\d+" missed="\d+"' | awk '{c+=$1; m+=$2} END {print c / (c + m) * 100}' FS='[="]' OFMT="%.2f")
          echo "Cobertura de líneas: ${LINE_COVERAGE}%"
