name: Test & Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with coverage
        run: mvn clean verify

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Show test coverage
        run: |
          if [ -f target/site/jacoco/jacoco.xml ]; then
            COVERAGE_LINE=$(grep '<counter type="LINE"' target/site/jacoco/jacoco.xml)
            if [ -z "$COVERAGE_LINE" ]; then
              echo "No se encontró ningún contador de líneas en jacoco.xml"
              exit 0
            fi
          
            COVERED=$(echo "$COVERAGE_LINE" | grep -oP 'covered="\K[0-9]+' | paste -sd+ - | bc)
            MISSED=$(echo "$COVERAGE_LINE" | grep -oP 'missed="\K[0-9]+' | paste -sd+ - | bc)
            TOTAL=$((COVERED + MISSED))
          
            if [ "$TOTAL" -gt 0 ]; then
              COVERAGE=$(awk "BEGIN { printf \"%.2f\", ($COVERED / $TOTAL) * 100 }")
              echo "Cobertura de líneas: $COVERAGE%"
            else
              echo "No se pudo calcular la cobertura (total de líneas = 0)"
            fi
          else
            echo "Archivo jacoco.xml no encontrado. Asegúrate de que 'mvn verify' lo genera correctamente."
          fi
          
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

