name: Test & Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with coverage
        run: mvn clean verify

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Show detailed test coverage
        run: |
          if [ -f target/site/jacoco/jacoco.xml ]; then
            LINE_COVERED=$(grep '<counter type="LINE"' target/site/jacoco/jacoco.xml | grep -oP 'covered="\K[0-9]+' | paste -sd+ - | bc)
            LINE_MISSED=$(grep '<counter type="LINE"' target/site/jacoco/jacoco.xml | grep -oP 'missed="\K[0-9]+' | paste -sd+ - | bc)
            LINE_TOTAL=$((LINE_COVERED + LINE_MISSED))
          
            INSTR_COVERED=$(grep '<counter type="INSTRUCTION"' target/site/jacoco/jacoco.xml | grep -oP 'covered="\K[0-9]+' | paste -sd+ - | bc)
            INSTR_MISSED=$(grep '<counter type="INSTRUCTION"' target/site/jacoco/jacoco.xml | grep -oP 'missed="\K[0-9]+' | paste -sd+ - | bc)
            INSTR_TOTAL=$((INSTR_COVERED + INSTR_MISSED))
          
            if [ "$LINE_TOTAL" -gt 0 ]; then
              LINE_PCT=$(awk "BEGIN { printf \"%.2f\", ($LINE_COVERED / $LINE_TOTAL) * 100 }")
              echo "Cobertura de líneas: $LINE_PCT%"
            else
              echo "No se pudo calcular cobertura de líneas (total=0)"
            fi
          
            if [ "$INSTR_TOTAL" -gt 0 ]; then
              INSTR_PCT=$(awk "BEGIN { printf \"%.2f\", ($INSTR_COVERED / $INSTR_TOTAL) * 100 }")
              echo "Cobertura de instrucciones: $INSTR_PCT%"
            else
              echo "No se pudo calcular cobertura de instrucciones (total=0)"
            fi
          else
            echo "Archivo jacoco.xml no encontrado."
          fi


